### ISSUE TITLE
没办发自动跳过已完成的任务

### ISSUE THREAD

**Issue by ZhiYhi** [dyhhhhhh/read_gk#1]
没办法自动跳过已完成的任务

**Comment by ZhiYhi** [comment]
没办法自动跳过已完成的任务

**Comment by 2468785842** [comment]
试试我写的吗? https://github.com/2468785842/ImsTech 自动化测试框架写的

**Comment by dyhhhhhh** [comment]
好的，我学习一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dyhhhhhh/read_gk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月15日(星期二) 上午10:42
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [dyhhhhhh/read_gk] 没办发自动跳过已完成的任务 (Issue #1)





 
试试我写的吗? https://github.com/2468785842/ImsTech 自动化测试框架写的

**Comment by dyhhhhhh** [comment]
> 没办法自动跳过已完成的任务



> 没办法自动跳过已完成的任务

现在可以跳过已完成的任务了

**Comment by dyhhhhhh** [comment]
已解决
